import type { Metadata } from "next";
import "./globals.css";
import { Magra } from "next/font/google";

const magra = Magra({
  variable: "--font-magra",
  subsets: ["latin"],
  weight: ["400", "700"],
});
import NavContainer from "@/components/Home/Navbar/NavContainer";

// Using system font 'Century Gothic' instead of Geist.

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${magra.variable} antialiased `}>
        <NavContainer />
        {children}
      </body>
    </html>
  );
}
